module Problems
  # Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  # By starting with 1 and 2, the first 10 terms will be:
  #
  # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  #
  # By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  # find the sum of the even-valued terms.
  class Problem2
    def execute(exceed_value)
      numbers = [1, 1]
      sum = 0
      begin
        next_number = Common.sum(numbers)
        if is_even?(next_number)
          sum += next_number
        end
        numbers << next_number
        numbers.shift
      end while (next_number < exceed_value)
      return sum
    end

    private
    def is_even?(number)
      number % 2 == 0
    end
  end
end